/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hashtable;

import java.util.Arrays;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());



        HashTable test = new HashTable(10);

        test.add(0,"test adding");
//        System.out.println(Arrays.toString(test.hash));
//        System.out.println(test.hash[0].value.toString());
        System.out.println(test.get(0));


    }
}
