/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hashtable;

import org.junit.jupiter.api.Test;

import java.util.Arrays;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");


//        Adding a key/value to your hashtable results in the value being in the data structure
        HashTable test = new HashTable(10);

        test.add("hi","test adding");
        assertEquals(true ,test.contains("hi"));




//        Retrieving based on a key returns the value stored
        assertEquals("test adding",test.get("hi"));



//        Successfully returns null for a key that does not exist in the hashtable
        assertEquals(" Wrong Key",test.get("hello"));


//        Successfully handle a collision within the hashtable
        test.add("a","hello");
        test.add(97,"another one");

        assertEquals("hello",test.get("a"));
        assertEquals("another one",test.get(97));


//        Successfully retrieve a value from a bucket within the hashtable that has a collision
        assertEquals("hello",test.get("a"));



//        Successfully hash a key to an in-range value
        assertEquals(9,test.hashStringKey("hi"));

    }
}
