/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hashtable;

import org.junit.jupiter.api.Test;

import java.util.Arrays;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");


//        Adding a key/value to your hashtable results in the value being in the data structure
        HashTable test = new HashTable(10);

        test.add("hi","test adding");
        assertEquals(true ,test.contains("hi"));




//        Retrieving based on a key returns the value stored
        assertEquals("test adding",test.get("hi"));



//        Successfully returns null for a key that does not exist in the hashtable
        assertEquals(" Wrong Key",test.get("hello"));


//        Successfully handle a collision within the hashtable
        test.add("a","hello");
        test.add(97,"another one");

        assertEquals("hello",test.get("a"));
        assertEquals("another one",test.get(97));


//        Successfully retrieve a value from a bucket within the hashtable that has a collision
        assertEquals("hello",test.get("a"));



//        Successfully hash a key to an in-range value
        assertEquals(9,test.hashStringKey("hi"));




    // challenge 31 :hashmap-repeated-word -->
      HashRepeated hash =new HashRepeated();
      String hashWords =" Once upon a time , there was a brave princess who...";
      assertEquals("a",hash.repeatedWord(hashWords));

      String hashWordsOne =" \" It was the best of times, it was the worst of times, it was the age of wisdom, it was the age of foolishness, it was the epoch of belief, it was the epoch of incredulity, it was the season of Light, it was the season of Darkness, it was the spring of hope, it was the winter of despair, we had everything before us, we had nothing before us, we were all going direct to Heaven, we were all going direct the other way – in short, the period was so far like the present period, that some of its noisiest authorities insisted on its being received, for good or for evil, in the superlative degree of comparison only...\"";
      assertEquals("it",hash.repeatedWord(hashWordsOne));

      String hashWordsTwo =" It was a queer,sultry summer , the summer they electrocuted the Rosenbergs , and I didn’t know what I was doing in New York...";
      assertEquals("summer",hash.repeatedWord(hashWordsTwo));

    }
}
