/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package stack.and.queue;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {

        System.out.println(new App().getGreeting());

        Stack <Integer> stack = new Stack<>();

        System.out.println(stack.isEmpty());
        stack.push(5);
        System.out.println(stack.pop());
        System.out.println(stack.pop());

        Queue <Integer> q = new Queue<>();
        q.enqueue(4);
        System.out.println(q.front.value);
        System.out.println(q.back.value);
        System.out.println(q.dequeue());





    }
}
