/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package insertion.sort;

import org.junit.jupiter.api.Test;

import java.util.Arrays;

import static insertion.sort.App.insertionSort;
import static insertion.sort.App.quickSort;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");


        int[] array = {8,4,23,42,16,15};
        int[] arrayOne = {};
        int[] arrayTwo = {};
        int []arrayThree={4,8,15,16,23,42};

        assertEquals(Arrays.toString(arrayThree),Arrays.toString(insertionSort(array)));

        assertEquals(Arrays.toString(arrayOne),Arrays.toString(insertionSort(arrayTwo)));



        int[] quickArray = {15, 12, 7, 6, 5, 7};
        int[] result = {5,6,7,7,12,15};
        assertEquals(Arrays.toString(result),Arrays.toString(quickSort(quickArray,0,5)));
    }
}
